version: "3.0"

# Expose ports locally for dev
services:
  freeswitch:
    image: ensemblepourladifference/freeswitch:latest
    build:
      context: .
      dockerfile: ./Dockerfile-freeswitch
    restart: unless-stopped

  mongo:
    ports:
      - "27017:27017"
    volumes:
      - './data/mongo:/data/db'
