version: '3.0'

# Expose ports locally for dev
services:
  freeswitch:
    image: ensemblepourladifference/freeswitch:latest
    build:
      context: packages/freeswitch
    ports:
      - '8021:8021/tcp'
      - '5060:5060/tcp'
      - '5060:5060/udp'
      - '5080:5080/tcp'
      - '5080:5080/udp'
      - '5061:5061/tcp'
      - '5061:5061/udp'
      - '5081:5081/tcp'
      - '5081:5081/udp'
      - '7443:7443/tcp'
      - '5070:5070/tcp'
      - '5070:5070/udp'
    restart: unless-stopped
  mongo:
    ports:
      - '27017:27017'
    volumes:
      - './data/mongo:/data/db'
  salama-freeswitch-controller:
    build: packages/salama-freeswitch-controller
    restart: unless-stopped
    network_mode: host
    container_name: salama-freeswitch-controller
    environment:
      - FREESWITCH_IP=127.0.0.1
      - FREESWITCH_PORT=8021
      - FREESWITCH_PASSWORD=ClueCon
