version: '3.0'

services:
  salama-mgnt:
    image: ensemblepourladifference/salama-mgnt:latest
    build: packages/salama-mgnt
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://mongo/salama-mgnt
  salama-freeswitch-controller:
    build: packages/salama-freeswitch-controller
    restart: unless-stopped
    network_mode: host
    container_name: salama-freeswitch-controller
    environment:
      - REDIS_HOST=redis
      - FREESWITCH_IP=127.0.0.1
      - FREESWITCH_PORT=8021
      - FREESWITCH_PASSWORD=ClueCon
  osmo-msc:
    image: ensemblepourladifference/osmo-msc:latest
    build:
      context: packages/osmo-msc-latest
    network_mode: 'host'
    restart: unless-stopped
  osmo-mgw:
    image: ensemblepourladifference/osmo-mgw:latest
    build:
      context: packages/osmo-mgw-latest
    network_mode: 'host'
    restart: unless-stopped
  osmo-hlr:
    image: ensemblepourladifference/osmo-hlr:latest
    build:
      context: packages/osmo-hlr-latest
    network_mode: 'host'
    restart: unless-stopped
  osmo-stp:
    image: ensemblepourladifference/osmo-stp:latest
    build:
      context: packages/osmo-stp-latest
    network_mode: 'host'
    restart: unless-stopped
