libosmovty: VTY (Virtual TTY) interface
VTY (Virtual TTY) interface
Files
file vty.h
Data Structures
struct vty
struct vty_app_info
struct vty_signal_data
Macros
#define VTY_PRINTF_ATTRIBUTE(a, b)
#define ERRNO_IO_RETRY(EN) (((EN) == EAGAIN) || ((EN) == EWOULDBLOCK) || ((EN) == EINTR))
#define VTY_READ_BUFSIZ 512
#define VTY_BUFSIZ 512
#define VTY_MAXHIST 20
#define VTY_NEWLINE ((vty->type == VTY_TERM) ? "\r\n" : "\n")
Enumerations
enum event {
VTY_SERV, VTY_READ, VTY_WRITE, VTY_CLOSED,
VTY_TIMEOUT_RESET
}
VTY events.
enum vty_type { VTY_TERM, VTY_FILE, VTY_SHELL, VTY_SHELL_SERV }
enum signal_vty { S_VTY_EVENT }
Functions
static const char * vty_newline (struct vty *vty)
void vty_init (struct vty_app_info *app_info)
Initialize VTY layer.
int vty_read_config_file (const char *file_name, void *priv)
Read the configuration file using the VTY code.
void vty_init_vtysh (void)
void vty_reset (void)
Reset all VTY status.
struct vty * vty_new (void)
Allocate a new vty interface structure.
struct vty * vty_create (int vty_sock, void *priv)
Create new vty structure.
int vty_out (struct vty *, const char *,...) VTY_PRINTF_ATTRIBUTE(2
int int vty_out_newline (struct vty *)
print a newline on the given VTY
int vty_read (struct vty *vty)
Read data via vty socket.
void vty_close (struct vty *)
Close a given vty interface.
char * vty_get_cwd (void)
void vty_log (const char *level, const char *proto, const char *fmt, va_list)
int vty_config_lock (struct vty *)
Lock the configuration to a given VTY.
int vty_config_unlock (struct vty *)
Unlock the configuration from a given VTY.
int vty_shell (struct vty *)
Return if this VTY is a shell or not.
int vty_shell_serv (struct vty *)
void vty_hello (struct vty *)
void * vty_current_index (struct vty *)
return the current index of a given VTY
int vty_current_node (struct vty *vty)
return the current node of a given VTY
int vty_go_parent (struct vty *vty)
const char * vty_get_bind_addr (void)
Variables
void * tall_vty_ctx
struct cmd_element cfg_description_cmd
struct cmd_element cfg_no_description_cmd
Detailed Description
Enumeration Type Documentation
enum signal_vty
signal handling
Function Documentation
int vty_config_lock (struct vty * vty)
Lock the configuration to a given VTY.
Parameters
[in] vty VTY to which the config shall be locked
Returns
1 on success, 0 on error
This shall be used to make sure only one VTY at a given time has access to modify the configuration
References config.
int vty_config_unlock (struct vty * vty)
Unlock the configuration from a given VTY.
Parameters
[in] vty VTY from which the configuration shall be unlocked
Returns
0 in case of success
References config.
Referenced by vty_close().
void vty_init (struct vty_app_info * app_info)
Initialize VTY layer.
Parameters
[in] app_info application information
References host::app_info, CONFIG_NODE, ENABLE_NODE, install_element(), install_node(), vty_app_info::tall_ctx, and VTY_NODE.
int vty_read_config_file (const char * file_name, void * priv)
Read the configuration file using the VTY code.
Parameters
[in] file_name file name of the configuration file
[in] priv private data to be passed to vty_read_file