libosmocore: Simple doubly linked list implementation
Simple doubly linked list implementation
Files
file linuxlist.h
Simple doubly linked list implementation.
Data Structures
struct llist_head
(double) linked list header structure
Macros
#define inline __inline__
#define container_of(ptr, type, member)
cast a member of a structure out to the containing structure
#define LLIST_POISON1 ((void *) 0x00100100)
#define LLIST_POISON2 ((void *) 0x00200200)
#define LLIST_HEAD_INIT(name) { &(name), &(name) }
#define LLIST_HEAD(name) struct llist_head name = LLIST_HEAD_INIT(name)
define a statically-initialized llist_head
#define INIT_LLIST_HEAD(ptr)
initialize a llist_head to point back to self
#define llist_entry(ptr, type, member) container_of(ptr, type, member)
Get the struct containing this list entry.
#define llist_for_each(pos, head)
Iterate over a linked list.
#define __llist_for_each(pos, head) for (pos = (head)->next; pos != (head); pos = pos->next)
Iterate over a llist (no prefetch)
#define llist_for_each_prev(pos, head)
Iterate over a llist backwards.
#define llist_for_each_safe(pos, n, head)
Iterate over a list; safe against removal of llist entry.
#define llist_for_each_entry(pos, head, member)
Iterate over llist of given type.
#define llist_for_each_entry_reverse(pos, head, member)
Iterate backwards over llist of given type.
#define llist_for_each_entry_continue(pos, head, member)
iterate over llist of given type continuing after existing point
#define llist_for_each_entry_safe(pos, n, head, member)
iterate over llist of given type, safe against removal of non-consecutive(!) llist entries
#define llist_for_each_rcu(pos, head)
#define __llist_for_each_rcu(pos, head)
#define llist_for_each_safe_rcu(pos, n, head)
#define llist_for_each_entry_rcu(pos, head, member)
#define llist_for_each_continue_rcu(pos, head)
Functions
static void prefetch (const void *x)
static void __llist_add (struct llist_head *_new, struct llist_head *prev, struct llist_head *next)
Insert a new entry between two known consecutive entries.
static void llist_add (struct llist_head *_new, struct llist_head *head)
add a new entry into a linked list (at head)
static void llist_add_tail (struct llist_head *_new, struct llist_head *head)
add a new entry into a linked list (at tail)
static void __llist_del (struct llist_head *prev, struct llist_head *next)
static void llist_del (struct llist_head *entry)
Delete entry from linked list.
static void llist_del_init (struct llist_head *entry)
Delete entry from linked list and reinitialize it.
static void llist_move (struct llist_head *llist, struct llist_head *head)
Delete from one llist and add as another's head.
static void llist_move_tail (struct llist_head *llist, struct llist_head *head)
Delete from one llist and add as another's tail.
static int llist_empty (const struct llist_head *head)
Test whether a linked list is empty.
static void __llist_splice (struct llist_head *llist, struct llist_head *head)
static void llist_splice (struct llist_head *llist, struct llist_head *head)
Join two llists.
static void llist_splice_init (struct llist_head *llist, struct llist_head *head)
join two llists and reinitialise the emptied llist.
static unsigned int llist_count (struct llist_head *head)
count nr of llist items by iterating.
Variables
struct llist_head * llist_head::next
Pointer to next and previous item.
struct llist_head * llist_head::prev
Detailed Description
Macro Definition Documentation
#define __llist_for_each (pos, head) for (pos = (head)->next; pos != (head); pos = pos->next)
Iterate over a llist (no prefetch)
Parameters
pos The llist_head to use as a loop counter
head The head of the list over which to iterate
This variant differs from llist_for_each() in that it's the simplest possible llist iteration code, no prefetching is done. Use this for code that knows the llist to be very short (empty or 1 entry) most of the time.
#define __llist_for_each_rcu (pos, head)
Value:
for (pos = (head)->next; pos != (head); \
                pos = pos->next, ({ smp_read_barrier_depends(); 0;}))
#define container_of (ptr, type, member)
Value:
({                      \
        const typeof( ((type *)0)->member ) *__mptr = (ptr);    \
        (type *)( (char *)__mptr - offsetof(type, member) );})
cast a member of a structure out to the containing structure
Parameters
[in] ptr the pointer to the member.
[in] type the type of the container struct this is embedded in.
[in] member the name of the member within the struct.
Referenced by osmo_timers_prepare(), osmo_timers_update(), and osmo_wqueue_bfd_cb().
#define INIT_LLIST_HEAD (ptr)
Value:
do { \
        (ptr)->next = (ptr); (ptr)->prev = (ptr); \
} while (0)
initialize a llist_head to point back to self
Referenced by llist_del_init(), llist_splice_init(), log_target_create(), osmo_fsm_inst_alloc(), osmo_fsm_register(), osmo_timer_add(), osmo_timers_update(), and osmo_wqueue_init().
#define llist_entry (ptr, type, member) container_of(ptr, type, member)
Get the struct containing this list entry.
Parameters
ptr The llist_head pointer
type The type of the struct this is embedded in
@member The name of the llist_head within the struct
Referenced by _osmo_fsm_inst_term_children(), and msgb_dequeue().
#define llist_for_each (pos, head)
Value:
for (pos = (head)->next, prefetch(pos->next); pos != (head); \
                pos = pos->next, prefetch(pos->next))
Iterate over a linked list.
Parameters
pos The llist_head to use as a loop counter
head The head of the list over which to iterate
Referenced by llist_count().
#define llist_for_each_continue_rcu (pos, head)
Value:
for ((pos) = (pos)->next, prefetch((pos)->next); (pos) != (head); \
                (pos) = (pos)->next, ({ smp_read_barrier_depends(); 0;}), prefetch((pos)->next))
llist_for_each_continue_rcu - iterate over an rcu-protected llist continuing after existing point. : the &struct llist_head to use as a loop counter. : the head for your llist.
#define llist_for_each_entry (pos, head, member)
Value:
for (pos = llist_entry((head)->next, typeof(*pos), member),     \
                     prefetch(pos->member.next);                        \
             &pos->member != (head);                                    \
             pos = llist_entry(pos->member.next, typeof(*pos), member), \
                     prefetch(pos->member.next))
Iterate over llist of given type.
Parameters
pos The 'type *' to use as a loop counter
head The head of the list over which to iterate
member The name of the llist_head within struct pos
Referenced by log_check_level(), log_target_find(), log_targets_reopen(), osmo_counter_get_by_name(), osmo_counters_for_each(), osmo_signal_dispatch(), osmo_signal_unregister_handler(), osmo_stat_item_get_group_by_name_idx(), osmo_timers_update(), osmo_vlogp(), rate_ctr_for_each_group(), and rate_ctr_get_group_by_name_idx().
#define llist_for_each_entry_continue (pos, head, member)
Value:
for (pos = llist_entry(pos->member.next, typeof(*pos), member), \
                     prefetch(pos->member.next);                        \
             &pos->member != (head);                                    \
             pos = llist_entry(pos->member.next, typeof(*pos), member), \
                     prefetch(pos->member.next))
iterate over llist of given type continuing after existing point
Parameters
pos The 'type *' to use as a loop counter
head The head of the list over which to iterate
member The name of the llist_head within struct pos
#define llist_for_each_entry_rcu (pos, head, member)
Value:
for (pos = llist_entry((head)->next, typeof(*pos), member),     \
                     prefetch(pos->member.next);                        \
             &pos->member != (head);                                    \
             pos = llist_entry(pos->member.next, typeof(*pos), member), \
                     ({ smp_read_barrier_depends(); 0;}),               \
                     prefetch(pos->member.next))
llist_for_each_entry_rcu - iterate over rcu llist of given type : the type * to use as a loop counter. : the head for your llist. : the name of the llist_struct within the struct.
#define llist_for_each_entry_reverse (pos, head, member)
Value:
for (pos = llist_entry((head)->prev, typeof(*pos), member),     \
                     prefetch(pos->member.prev);                        \
             &pos->member != (head);                                    \
             pos = llist_entry(pos->member.prev, typeof(*pos), member), \
                     prefetch(pos->member.prev))
Iterate backwards over llist of given type.
Parameters
pos The 'type *' to use as a loop counter
head The head of the list over which to iterate
member The name of the llist_head within struct pos
#define llist_for_each_entry_safe (pos, n, head, member)
Value:
for (pos = llist_entry((head)->next, typeof(*pos), member),     \
                n = llist_entry(pos->member.next, typeof(*pos), member);        \
             &pos->member != (head);                                    \
             pos = n, n = llist_entry(n->member.next, typeof(*n), member))
iterate over llist of given type, safe against removal of non-consecutive(!) llist entries
Parameters
pos The 'type *' to use as a loop counter
n Another type * to use as temporary storage
head The head of the list over which to iterate
member The name of the llist_head within struct pos
#define llist_for_each_prev (pos, head)
Value:
for (pos = (head)->prev, prefetch(pos->prev); pos != (head); \
                pos = pos->prev, prefetch(pos->prev))
Iterate over a llist backwards.
Parameters
pos The llist_head to use as a loop counter
head The head of the list over which to iterate
#define llist_for_each_rcu (pos, head)
Value:
for (pos = (head)->next, prefetch(pos->next); pos != (head); \
                pos = pos->next, ({ smp_read_barrier_depends(); 0;}), prefetch(pos->next))
llist_for_each_rcu - iterate over an rcu-protected llist : the &struct llist_head to use as a loop counter. : the head for your llist.
#define llist_for_each_safe (pos, n, head)
Value:
for (pos = (head)->next, n = pos->next; pos != (head); \
                pos = n, n = pos->next)
Iterate over a list; safe against removal of llist entry.
Parameters
pos The llist_head to use as a loop counter
n Another llist_head to use as temporary storage
head The head of the list over which to iterate
#define llist_for_each_safe_rcu (pos, n, head)
Value:
for (pos = (head)->next, n = pos->next; pos != (head); \
                pos = n, ({ smp_read_barrier_depends(); 0;}), n = pos->next)
llist_for_each_safe_rcu - iterate over an rcu-protected llist safe against removal of llist entry : the &struct llist_head to use as a loop counter.
: another &struct llist_head to use as temporary storage : the head for your llist.
#define LLIST_HEAD (name) struct llist_head name = LLIST_HEAD_INIT(name)
define a statically-initialized llist_head
Parameters
[in] name Variable name
This is a helper macro that will define a named variable of type llist_head and initialize it
#define LLIST_POISON1 ((void *) 0x00100100)
These are non-NULL pointers that will result in page faults under normal circumstances, used to verify that nobody uses non-initialized llist entries.
Referenced by llist_del().
Function Documentation
static void __llist_add (struct llist_head * _new, struct llist_head * prev, struct llist_head * next) inline static
Insert a new entry between two known consecutive entries.
This is only for internal llist manipulation where we know the prev/next entries already!
References llist_head::next.
Referenced by llist_add(), and llist_add_tail().
static void llist_add (struct llist_head * _new, struct llist_head * head) inline static
add a new entry into a linked list (at head)
Parameters
_new New entry to be added
head llist_head to add it after
Insert a new entry after the specified head. This is good for implementing stacks.
References __llist_add(), and llist_head::next.
Referenced by llist_move(), osmo_fsm_inst_alloc(), osmo_fsm_inst_alloc_child(), osmo_stat_item_group_alloc(), osmo_timers_update(), and rate_ctr_group_alloc().
static void llist_add_tail (struct llist_head * _new, struct llist_head * head) inline static
add a new entry into a linked list (at tail)
Parameters
_new New entry to be added
head Head of linked list to whose tail we shall add _new
Insert a new entry before the specified head. This is useful for implementing queues.
References __llist_add().
Referenced by llist_move_tail(), log_add_target(), msgb_enqueue(), osmo_counter_alloc(), osmo_fsm_register(), and osmo_signal_register_handler().
static unsigned int llist_count (struct llist_head * head) inline static
count nr of llist items by iterating.
Parameters
head The llist head to count items of.
Returns
Number of items.
This function is not efficient, mostly useful for small lists and non time critical cases like unit tests.
References llist_for_each.
static void llist_del (struct llist_head * entry) inline static
Delete entry from linked list.
Parameters
entry The element to delete from the llist
Note: llist_empty on entry does not return true after this, the entry is in an undefined state.
References LLIST_POISON1, and llist_head::next.
Referenced by _osmo_fsm_inst_term(), log_del_target(), msgb_dequeue(), osmo_counter_free(), osmo_fsm_inst_free(), osmo_fsm_unregister(), osmo_signal_unregister_handler(), osmo_stat_item_group_free(), and rate_ctr_group_free().
static void llist_del_init (struct llist_head * entry) inline static
Delete entry from linked list and reinitialize it.
Parameters
entry The element to delete from the list
References INIT_LLIST_HEAD, and llist_head::next.
Referenced by osmo_timer_del().
static int llist_empty (const struct llist_head * head) inline static
Test whether a linked list is empty.
Parameters
[in] head The llist to test.
Returns
1 if the list is empty, 0 otherwise
References llist_head::next.
Referenced by _osmo_fsm_inst_term_children(), llist_splice(), llist_splice_init(), msgb_dequeue(), osmo_timer_del(), osmo_wqueue_bfd_cb(), and osmo_wqueue_clear().
static void llist_move (struct llist_head * llist, struct llist_head * head) inline static
Delete from one llist and add as another's head.
Parameters
llist The entry to move
head The head that will precede our entry
References llist_add(), and llist_head::next.
static void llist_move_tail (struct llist_head * llist, struct llist_head * head) inline static
Delete from one llist and add as another's tail.
Parameters
llist The entry to move
head The head that will follow our entry
References llist_add_tail(), and llist_head::next.
static void llist_splice (struct llist_head * llist, struct llist_head * head) inline static
Join two llists.
Parameters
llist The new linked list to add
head The place to add llist in the other list
References llist_empty().
static void llist_splice_init (struct llist_head * llist, struct llist_head * head) inline static
join two llists and reinitialise the emptied llist.
Parameters
llist The new linked list to add.
head The place to add it in the first llist.
The llist at is reinitialised
References INIT_LLIST_HEAD, and llist_empty().